const exampleProjectId = 'foldboard-example';
const exampleProjectName = 'Example project';

/// Editable example of one path through nested levels.
Map<String, dynamic> exampleProjectDocument() => {
  'nodes': [
    {
      'id': 'product-goal',
      'title': 'Product goal',
      'description': 'Set the outcome and constraints for the plan.',
      'x': 120,
      'y': 300,
    },
    {
      'id': 'human-direction',
      'title': 'Human direction',
      'description': 'Define the goal and constraints for this level.',
      'parentId': 'build-together',
      'x': 160,
      'y': 260,
    },
    {
      'id': 'agent-plan',
      'title': 'Agent plan',
      'description': 'Plan within this fold’s bounded context.',
      'parentId': 'build-together',
      'x': 500,
      'y': 260,
    },
    {
      'id': 'risk-check',
      'title': 'Risk check',
      'description': 'Challenge assumptions before implementation starts.',
      'parentId': 'build-together',
      'x': 500,
      'y': 470,
    },
    {
      'id': 'team-review',
      'title': 'Team review',
      'description': 'People review the proposal and choose the next step.',
      'parentId': 'build-together',
      'x': 840,
      'y': 260,
    },
    {
      'id': 'quality-checks',
      'title': 'Quality checks',
      'description': 'Test the important paths and inspect the result.',
      'parentId': 'ship-safely',
      'x': 420,
      'y': 280,
    },
    {
      'id': 'release',
      'title': 'Release',
      'description': 'Ship the reviewed change.',
      'parentId': 'ship-safely',
      'x': 760,
      'y': 280,
    },
    {
      'id': 'observe',
      'title': 'Observe',
      'description': 'Watch real usage and capture what happens next.',
      'parentId': 'ship-safely',
      'x': 1100,
      'y': 280,
    },
    {
      'id': 'customer-learning',
      'title': 'Customer learning',
      'description': 'Evidence feeds the next product decision.',
      'x': 1000,
      'y': 300,
    },
  ],
  'groups': [
    {
      'id': 'build-together',
      'title': 'Build together',
      'description': 'A shared context for a person and agent.',
      'x': 560,
      'y': 300,
      'width': 1320,
      'height': 720,
    },
    {
      'id': 'ship-safely',
      'title': 'Ship safely',
      'description': 'A nested context for verification and release.',
      'parentId': 'build-together',
      'x': 1180,
      'y': 260,
      'width': 1100,
      'height': 560,
    },
  ],
  'edges': [
    {'id': 'goal-direction', 'from': 'product-goal', 'to': 'human-direction'},
    {'id': 'direction-plan', 'from': 'human-direction', 'to': 'agent-plan'},
    {'id': 'plan-review', 'from': 'agent-plan', 'to': 'team-review'},
    {'id': 'plan-risk', 'from': 'agent-plan', 'to': 'risk-check'},
    {'id': 'risk-review', 'from': 'risk-check', 'to': 'team-review'},
    {'id': 'review-checks', 'from': 'team-review', 'to': 'quality-checks'},
    {'id': 'checks-release', 'from': 'quality-checks', 'to': 'release'},
    {'id': 'release-observe', 'from': 'release', 'to': 'observe'},
    {'id': 'observe-learning', 'from': 'observe', 'to': 'customer-learning'},
  ],
};
